# conda env create -f environment.yml
name: water
dependencies:
  - python=3.7
  - tensorflow-gpu=2.0.0
  - keras
  - cudatoolkit
  - notebook
  - ipykernel
  - matplotlib
  - numpy
  - opencv
  - gdal
  - pip
  - pip:
      - googledrivedownloader
      - tifffile
      - requests

      
  
